### ISSUE TITLE
Issue with playback in Store version

### ISSUE THREAD

**Issue by wiired24** [aboe026/boxify#69]
Just to let you know Adam there is a issue with the store version where the tracks will fail to load using Youtube as the music source. Perhaps you forgot to enter valid credentials for the Youtube API Key? Or maybe you forgot to enable the Youtube Data API? I Wanted to let you know so this could get resolved as soon as possible. Or If you'd like I could send you my pre compiled binary of boxify which has the Data API enabled and has valid credentials (It works flawlessly) and you could update the current version on the store with that.

**Comment by aboe026** [comment]
Thanks @wiired24, looks like we reached our YouTube API queries/day (1,000,000) quota. I've requested for more (5,000,000, hopefully that is enough?). Awaiting response from YouTube...

**Comment by wiired24** [comment]
Wow, Sounds like lots of people are enjoying your appp haha,

Alright glad to hear your on it. Hopefully you hear back from Youtube Soon

**Comment by aboe026** [comment]
I was also trying to use the YouTube Data .NET API, but couldn't get the NuGet package to import into the project. The .NET API allows for batch searches, which would reduce the number of queries. It is not written for UWP however, and it was removed earlier because of atrocious performance. Kind of frustrating that the YouTube REST/curl API v3 no longer allows for batch searching (deprecated from v2)

**Comment by aboe026** [comment]
Haven't heard back from YouTube yet. It looks like we've been fine though since the errors:
![image](https://user-images.githubusercontent.com/11340779/27414278-7f048f20-56ce-11e7-9f90-fce4367dff8d.png)
Not sure why we had such a large spike then (bots?). I'll try to submit another increase proposal to YouTube with a much less dramatic increase (just 500,000 more).

**Comment by aboe026** [comment]
YouTube denied our extension, citing we are not close to our query limit. Thankfully we haven't come very close to the limit since those two nights, which leads me to believe they were in fact from bots. I'll try and keep an eye on our quota usage and reapply for an extension if/when we get close again.
